// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment("WEB_API_KEY", defaultValue: ""),
    appId: '1:569688138097:web:26f66e62c98f3976a896d0',
    messagingSenderId: '569688138097',
    projectId: 'home-iot-bc949',
    authDomain: 'home-iot-bc949.firebaseapp.com',
    storageBucket: 'home-iot-bc949.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment("ANDROID_API_KEY", defaultValue: ""),
    appId: '1:569688138097:android:7c72cad85e79f2a8a896d0',
    messagingSenderId: '569688138097',
    projectId: 'home-iot-bc949',
    storageBucket: 'home-iot-bc949.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment("IOS_API_KEY", defaultValue: ""),
    appId: '1:569688138097:ios:d3db0177287d0335a896d0',
    messagingSenderId: '569688138097',
    projectId: 'home-iot-bc949',
    storageBucket: 'home-iot-bc949.appspot.com',
    iosBundleId: 'com.example.homeIot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment("MACOS_API_KEY", defaultValue: ""),
    appId: '1:569688138097:ios:d3db0177287d0335a896d0',
    messagingSenderId: '569688138097',
    projectId: 'home-iot-bc949',
    storageBucket: 'home-iot-bc949.appspot.com',
    iosBundleId: 'com.example.homeIot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment("WINDOWS_API_KEY", defaultValue: ""),
    appId: '1:569688138097:web:fe8b33a0b3ad232da896d0',
    messagingSenderId: '569688138097',
    projectId: 'home-iot-bc949',
    authDomain: 'home-iot-bc949.firebaseapp.com',
    storageBucket: 'home-iot-bc949.appspot.com',
  );
}
